language: java

# we test at Ubuntu Trusty (Ubuntu 14.04 LTS)
# see https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

# update to latest Java8 as described at https://github.com/travis-ci/travis-ci/issues/4042#issuecomment-109756980
addons:
  apt:
    packages:
      # most recent Java8 - this makes the DK switcher obsolete - see https://github.com/travis-ci/travis-ci/issues/5897#issuecomment-218354129
      - oracle-java8-installer
      # MySQL 5.6 as desccribed at https://docs.travis-ci.com/user/database-setup/#MySQL-5.6
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      # Required for Oracle XE - according to http://www.creative-doing.de/category/oracle-database/article/install-oracle-11gr2-express-edition-ubuntu-1404-64-bit
      - libaio1
      - unixodbc

services:
  - postgresql
  - mysql

env:
  - GRADLE_OPTS=-Dorg.gradle.daemon=false

# skip installation as this is also done during the script step
install: true

before_script:
  - psql -c 'create database jabref;' -U postgres
  - mysql -u root -e 'create database jabref'

script:
  - scripts/install-oracle-express.sh
  - ./gradlew databaseTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
